### ISSUE TITLE
legacy.store.bulk_update() throws error

### ISSUE THREAD

**Issue by loopdeloop76** [exdatic/elasticstore#2]
I get this error in scienceOS workbench:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[32], line 1
----> 1 store.bulk_upsert(iter_papers(data_dir + '/S2/papers/diffs/update_files'), create=True, stats_only=True)

File /opt/conda/lib/python3.10/site-packages/elasticstore/legacy/store.py:65, in ensure_index_exists.<locals>.wrapper.<locals>.wrapped(*args, **kwargs)
     62 @functools.wraps(func)
     63 def wrapped(*args, **kwargs):
     64     items = cast(Store, args[0])
---> 65     items.index_create()
     66     return func(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/elasticstore/legacy/store.py:124, in Store.index_create(self)
    120 def index_create(self):
    121     """
    122     Creates the index if not exists.
    123     """
--> 124     if not self.index_exists():
    125         if self._mappings:
    126             mappings = mappings_to_dict(self._mappings)

File /opt/conda/lib/python3.10/site-packages/elasticstore/legacy/store.py:118, in Store.index_exists(self)
    114 """
    115 Checks whether the index exists.
    116 """
    117 resp = self._es.indices.exists(index=self._index)
--> 118 return resp.body

AttributeError: 'bool' object has no attribute 'body'

**Comment by zeitderforschung** [comment]
Korrekte elasticsearch version? >=8.x

**Comment by loopdeloop76** [comment]
Sorry, hatte zwar elasticstore geupdatet, aber musste danach noch das Notebook starten
